[tool.poetry]
name = "ml-playground"
version = "0.1.0"
description = ""
authors = []
license = "MIT"
readme = "README.md"
packages = [
  { include = "ml_playground" },
]

[tool.poetry.dependencies]
python = "^3.11"
torch = [
  {platform = "linux", version = "^2.0.1+cu118", source = "torch_cu118"},
  {platform = "darwin", version = "^2.0.1", source = "pypi"},
]
torchvision = [
  {platform = "linux", version = "^0.15.2+cu118", source = "torch_cu118"},
  {platform = "darwin", version = "^0.15.2", source = "pypi"},
]
torchaudio = [
  {platform = "linux", version = "^2.0.2+cu118", source = "torch_cu118"},
  {platform = "darwin", version = "^2.0.2", source = "pypi"},
]


[tool.poetry.group.dev.dependencies]
ipython = "^8.15.0"
ruff = "^0.0.290"
pyink = "^23.5.0"
isort = "^5.12.0"


[[tool.poetry.source]]
name = "torch_cu118"
url = "https://download.pytorch.org/whl/cu118"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
